import { GALLERY, PRIMARY_PHOTO, type GalleryPhoto } from "../content/gallery";
import { PERSON } from "../content/profile";

/**
 * Photograph album.
 *
 * Every image is served from the derivatives generated by `npm run photos`, as
 * `<picture>` with WebP first and a JPEG fallback, explicit intrinsic
 * width/height (so nothing shifts while loading), lazy loading below the fold
 * and a descriptive caption. The figure/figcaption pairing is what makes each
 * photograph legible to image search as a captioned entity rather than a
 * decorative asset.
 */
export function Gallery({
  photos = GALLERY,
  eagerFirst = false,
}: {
  photos?: GalleryPhoto[];
  eagerFirst?: boolean;
}) {
  if (photos.length === 0) return null;

  return (
    <ul className="gallery">
      {photos.map((photo, index) => (
        <li className="gallery__item" key={photo.id}>
          <figure className="gallery__figure">
            <picture>
              <source type="image/webp" srcSet={photo.webpSrcset} sizes={sizesFor(photo)} />
              <img
                src={photo.src}
                srcSet={photo.srcset}
                sizes={sizesFor(photo)}
                width={photo.width}
                height={photo.height}
                alt={photo.alt}
                loading={eagerFirst && index === 0 ? "eager" : "lazy"}
                decoding="async"
                className="gallery__img"
              />
            </picture>
            <figcaption className="gallery__caption">
              <span className="gallery__caption-text">{photo.caption}</span>
              {photo.location && (
                <span className="gallery__caption-place">{photo.location}</span>
              )}
            </figcaption>
          </figure>
        </li>
      ))}
    </ul>
  );
}

/** Responsive `sizes` hint, matched to the grid breakpoints in the stylesheet. */
function sizesFor(photo: GalleryPhoto): string {
  const isPortrait = photo.height > photo.width;
  return isPortrait
    ? "(max-width: 640px) 92vw, (max-width: 1000px) 46vw, 360px"
    : "(max-width: 640px) 92vw, (max-width: 1000px) 46vw, 520px";
}

/**
 * Hero portrait, drawn from the primary gallery photograph. Falls back to the
 * static plate in `public/portrait.jpg` when no photographs are installed, so
 * the layout is identical either way.
 */
export function PrimaryPortrait() {
  const photo = PRIMARY_PHOTO;
  const src = photo?.src ?? PERSON.photo;
  const webp = photo?.webp;
  const srcset = photo?.srcset;
  const webpSrcset = photo?.webpSrcset;

  return (
    <picture>
      {webp && <source type="image/webp" srcSet={webpSrcset} sizes="(max-width: 980px) 92vw, 420px" />}
      <img
        src={src}
        srcSet={srcset}
        sizes="(max-width: 980px) 92vw, 420px"
        width={photo?.width ?? 1200}
        height={photo?.height ?? 1500}
        alt={photo?.alt ?? PERSON.photoAlt}
        {...({ fetchpriority: "high" } as Record<string, string>)}
        decoding="async"
        className="hero__portrait"
      />
    </picture>
  );
}
